spring.application.name=broker-backend
server.port=8080
app.cors.allowed-origin=http://localhost:3000

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/broker_db?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# SQL initialization
spring.sql.init.mode=never

# Market data provider
alpha.vantage.api-key=${ALPHA_VANTAGE_API_KEY:4E5STC1D6287APKZ}

# JWT — token propio del backend
app.jwt.secret=${JWT_SECRET:broker_jwt_secret_cambia_esto_en_produccion_debe_ser_larga}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Google OAuth — Client ID para verificar Google ID Tokens
google.client-id=${GOOGLE_CLIENT_ID:613176549351-nqb0d9oilhvq48sdjh72ioemfhifle0s.apps.googleusercontent.com}
